# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - d356e73c-139c-5667-98eb-0a0bc8517097

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://sampleappaoaichatgpt.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_463238a44da34637aac5e4d2e5f0b883 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_79529d41932e423281e2a3935b088e68 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: sampleappaoaichatgpt.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_463238a44da34637aac5e4d2e5f0b883 }}/sample-app-aoai-chatgpt:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'd356e73c-139c-5667-98eb-0a0bc8517097'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_552f19ae15e24a4b971b7d688fece1c7 }}
        images: 'sampleappaoaichatgpt.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_463238a44da34637aac5e4d2e5f0b883 }}/sample-app-aoai-chatgpt:${{ github.sha }}'